  <div class="wrapper">
    <p>Animation entièrement réalisé en CSS. Merci de mettre à jour votre navigateur dans sa version la plus récente et de bannir Internet Explorer <sup><small><small>RIP Edge</small></small></sup>. La route est longue, mais la voie est libre.</p>
    <p>Réalisé par <a href="https://skullmasher.io">Florian "Skullmasher" Ledru</a>. Le code de ce site web est <a href="https://github.com/skullmasher/wish-card-2019">open source</a>.</p>
  </div>
