<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Personnaliser et partager  votre carte de voeux 2019.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Carte de voeux 2019</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="place-center">
    <div>
      <form method="post" action="">
        <header>
          <div class="site-hero wrapper wrapper--small">
            <h1>Carte de voeux 2019</h1>
            <p>Cliquer sur le texte dans le cadre pour composer votre message et ajouter votre signature. Une fois terminer cliquer sur le bouton partager situé après votre carte de voeux votre voeux.</p>
          </div>
        </header>
        <main>
          <div class="wishcard">
            <div class="wishcard__background">
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <header class="wishcard__sky">
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__stars"></div>
                <div class="wishcard__moon"></div>
              </header>
              <main class="wrapper wrapper--small">
                <div class="font-charm">
                  <div class="wishcard__message" contenteditable="">
                    <p>Chère visiteur,</p>
                    <p>Compose ton message içi pour partager tes meilleurs voeux.</p>
                  </div>
                  <div class="wishcard__signature" contenteditable="">
                    <p>Ma signature</p>
                  </div>
                </div>
              </main>
              <footer class="wishcard__floor">
                <div class="christmastree">
                  <div class="star-filter">
                    <div class="christmastree__star"></div>
                  </div>
                  <div class="christmastree__triangle"></div>
                  <div class="christmastree__triangle"></div>
                  <div class="christmastree__trunk"></div>
                </div>
                <div class="snowman">
                  <div class="snowman__hat">
                    <div class="snowman__pompon"></div>
                  </div>
                  <div class="snowman__head">
                    <div class="snowman__eyes">
                      <div class="snowman__eye snowman__eye--right"></div>
                      <div class="snowman__eye snowman__eye--left"></div>
                    </div>
                    <div class="snowman__nose"></div>
                    <div class="snowman__mouth">
                      <div class="snowman__rockteeth"></div>
                      <div class="snowman__rockteeth snowman__rockteeth--alternate"></div>
                      <div class="snowman__rockteeth"></div>
                      <div class="snowman__rockteeth snowman__rockteeth--alternate"></div>
                    </div>
                  </div>
                  <div class="snowman__body">
                    <div class="snowman__arm snowman__arm--left"></div>
                    <div class="snowman__trunk">
                      <div class="snowman__coat">
                        <div class="snowman__rockbutton"></div>
                        <div class="snowman__rockbutton"></div>
                        <div class="snowman__rockbutton"></div>
                        <div class="snowman__rockbutton"></div>
                      </div>
                    </div>
                    <div class="snowman__arm snowman__arm--right"></div>
                  </div>
                </div>
              </footer>
              <div class="wishcard__ground"></div>
            </div>
          </div>
        </main>
        <footer class="mbm place-center">
          <button class="btn btn--success btn--big">Partager mon voeux</button>
        </footer>
      </form>
    </div>
  </div>
  <footer class="site-footer">
    <div class="wrapper">
      <p>Réalisé par <a href="https://skullmasher.io">Skullmasher</a>. Le code de ce site web est <a href="https://github.com/skullmasher/wish-card-2019">opensource</a>.</p>
    </div>
  </footer>
  <script type="text/javascript" src="js/script.js"></script>
</body>
</html>
