<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Personnaliser et partager votre carte de voeux 2019.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Carte de voeux 2019</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="place-center">
    <div>
      <header>
        <div class="site-hero wrapper wrapper--small">
          <h1>Carte de voeux 2019</h1>
          <p>Cliquer sur le texte dans le cadre pour composer votre message et ajouter votre signature. Une fois terminer cliquer sur le bouton partager situé après votre carte de voeux votre voeux.</p>
        </div>
      </header>
      <main>
        <div class="wishcard">
          <div class="wishcard__background">
            <header class="wishcard__sky">
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__moon"></div>
            </header>
            <main class="wrapper wrapper--small">
              <div class="font-charm">
                <div class="wishcard__message js-wishText" contenteditable="">
                  <p>Chère visiteur,</p>
                  <p>Compose ton message ici pour partager tes meilleurs vœux.</p>
                </div>
                <div class="wishcard__signature js-wishSign" contenteditable="">
                  <p>Ma signature</p>
                </div>
              </div>
            </main>
            <footer class="wishcard__floor">
              <div class="christmastree">
                <div class="star-filter">
                  <div class="christmastree__star"></div>
                </div>
                <div class="christmastree__triangle"></div>
                <div class="christmastree__triangle"></div>
                <div class="christmastree__trunk"></div>
              </div>
              <div class="snowman">
                <div class="snowman__hat">
                  <div class="snowman__pompon"></div>
                </div>
                <div class="snowman__head">
                  <div class="snowman__eyes">
                    <div class="snowman__eye snowman__eye--right"></div>
                    <div class="snowman__eye snowman__eye--left"></div>
                  </div>
                  <div class="snowman__nose"></div>
                  <div class="snowman__mouth">
                    <div class="snowman__rockteeth"></div>
                    <div class="snowman__rockteeth snowman__rockteeth--alternate"></div>
                    <div class="snowman__rockteeth"></div>
                    <div class="snowman__rockteeth snowman__rockteeth--alternate"></div>
                  </div>
                </div>
                <div class="snowman__body">
                  <div class="snowman__arm snowman__arm--left"></div>
                  <div class="snowman__trunk">
                    <div class="snowman__coat">
                      <div class="snowman__rockbutton"></div>
                      <div class="snowman__rockbutton"></div>
                      <div class="snowman__rockbutton"></div>
                      <div class="snowman__rockbutton"></div>
                    </div>
                  </div>
                  <div class="snowman__arm snowman__arm--right"></div>
                </div>
              </div>
            </footer>
            <div class="wishcard__ground"></div>
          </div>
        </div>
      </main>
      <footer class="wishcard__validation">
        <div class="wishcard__submit wrapper wrapper--small">
          <p class="color--muted js-wishWarn txtcenter">Pour partager votre voeux modifier le texte et la signature.</p>
          <div class="place-center">
            <button class="btn btn--success btn--big js-wishSubmit js-disabled">Partager mon voeux</button>
          </div>
        </div>
        <div class="wishcard__share wrapper wrapper--small">
          <p class="txtcenter mbm">Votre voeux est pret à être partager ! <a class="btn btn--small btn--success" href="topkek" target="_blank">VOIR</a></p>
          <div class="grid has-gutter mbm">
            <div class="share-wish__link">
              <p class="mbn">Lien de votre voeux.</p>
              <p class="share-wish__link js-shareWishLink" id="share-wish-link"><a href="topkek" target="_blank"><?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?></a></p>
            </div>
            <div class="share-wish__social">
              <p class="mbn">Partager ce site</p>
              <div class="flex-space-around">
                <a href="mailto:?Subject=Créer une carte de voeu 2019&amp;Body=https://skullmasher.io/wish-card-2019">mail</a>
                <a href="https://twitter.com/share?url=https://skullmasher.io/wish-card-2019" target="_blank">Twitter</a>
                <a href="http://www.facebook.com/sharer.php?u=https://skullmasher.io/wish-card-2019" target="_blank">Facebook</a>
              </div>
            </div>
          </div>
          <div class="txtcenter">
            <a class="btn btn--success" href="new">Créer un nouveaux vœux</a>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <footer class="site-footer">
    <?php require_once('footer_content.phtml') ?>
  </footer>

  <script type="text/javascript" src="js/script.js"></script>
</body>
</html>
