<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Personnaliser et partager  votre carte de voeux 2019.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Carte de voeux 2019</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body class="background--gradientgray">
  <div class="place-center">
    <div>
      <header>
        <div class="site-hero wrapper wrapper--small">
          <h1>Partager votre voeux</h1>
          <p><strong>Félicitations !</strong> votre voeux est pret à être partager.</p>
        </div>
      </header>
      <main>
        <div>
          <p>regarder votre voeux</p>
          <p><a href="#">https://skullmasher.io/wish-card-2019/ZAEjdsq098</a></p>
        </div>
        <div>
          <p><button class="btn">créer un nouveaux voeux</button></p>
        </div>
        <div>
          <p>Partager par mail</p>
          <p><a href="mailto:topkek@rarepepe.org">topkek@rarepepe.org</a></p>
        </div>
        <div>
          <p>Partager sur les réseaux sociaux</p>
          <p><a href="#">Twitter</a></p>
          <p><a href="#">Facebook</a></p>
        </div>
      </main>
    </div>
  </div>
  <footer class="site-footer">
    <div class="wrapper">
      <p>Réalisé par <a href="https://skullmasher.io">Skullmasher</a>. Le code de ce site web est <a href="https://github.com/skullmasher/wish-card-2019">opensource</a>.</p>
    </div>
  </footer>
</body>
</html>
