<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Personnaliser et partager  votre carte de voeux 2019.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Carte de voeux 2019</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="place-center">
    <div>
      <main class="mts">
        <div class="wishcard">
          <div class="wishcard__background">
            <header class="wishcard__sky">
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <div class="shooting-star"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__stars"></div>
              <div class="wishcard__moon"></div>
            </header>
            <main class="wrapper wrapper--small">
              <div class="font-charm">
                <div class="wishcard__message js-wishText">
                  <?php echo $message ?>
                </div>
                <div class="wishcard__signature js-wishSign">
                  <?php echo $signature ?>
                </div>
              </div>
            </main>
            <footer class="wishcard__floor">
              <div class="christmastree">
                <div class="star-filter">
                  <div class="christmastree__star"></div>
                </div>
                <div class="christmastree__triangle"></div>
                <div class="christmastree__triangle"></div>
                <div class="christmastree__trunk"></div>
              </div>
              <div class="snowman">
                <div class="snowman__hat">
                  <div class="snowman__pompon"></div>
                </div>
                <div class="snowman__head">
                  <div class="snowman__eyes">
                    <div class="snowman__eye snowman__eye--right"></div>
                    <div class="snowman__eye snowman__eye--left"></div>
                  </div>
                  <div class="snowman__nose"></div>
                  <div class="snowman__mouth">
                    <div class="snowman__rockteeth"></div>
                    <div class="snowman__rockteeth snowman__rockteeth--alternate"></div>
                    <div class="snowman__rockteeth"></div>
                    <div class="snowman__rockteeth snowman__rockteeth--alternate"></div>
                  </div>
                </div>
                <div class="snowman__body">
                  <div class="snowman__arm snowman__arm--left"></div>
                  <div class="snowman__trunk">
                    <div class="snowman__coat">
                      <div class="snowman__rockbutton"></div>
                      <div class="snowman__rockbutton"></div>
                      <div class="snowman__rockbutton"></div>
                      <div class="snowman__rockbutton"></div>
                    </div>
                  </div>
                  <div class="snowman__arm snowman__arm--right"></div>
                </div>
              </div>
            </footer>
            <div class="wishcard__ground"></div>
          </div>
        </div>
      </main>
    </div>
  </div>
  <?php require_once('footer.phtml') ?>
</body>
</html>
